### PR TITLE
Connectivity status; Restore state

### PR DESCRIPTION
**Pull request by lein1013**
I've add restore state for the buzzer and LED enable to keep behavior after a powercycle.
further I added the connectivity status to be able to see if the device is connected to the network

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
Thanks, Yeah I was gonna get to adding the status binary_sensor at some point.

Just note that `restore_state` only works on reboot/restart, but not after power loss.

**Review by jesserockz — CHANGES_REQUESTED** [review]
Happy to merge the status sensor in, but can you add the restore_states to a separate PR for consideration?

**Comment by lein1013** [comment]
No problem, 
based on your comment https://github.com/adonno/tagreader/pull/50#pullrequestreview-504396135 
I think it is OK to just remove it

**Review by jesserockz — APPROVED** [review]
Yeah thanks

**Pull request merged**
