### PR TITLE
Tidy up folder structure

### PR DESCRIPTION
**Pull request by Landrash**
Changes capitalization of folders to all be lower case.

### CODE REVIEW

**Comment by jesserockz** [comment]
Hi @Landrash Do you mind explaining the reason for this?

**Comment by Landrash** [comment]
Sure.

Simply for normalisation of folder structure. 

Had more minor suggestions but separated out individual features/changes by habit.

**Comment by jesserockz** [comment]
Yeah I understand that and I prefer lowercase folder too, but I also know that some filesystems don't take it well when you just change a file/folders casing in git and I have had issues with this in the past. Not sure if it is fixed in recent versions...

**Comment by Landrash** [comment]
Would an option be to rename the folders? 
Schematics -> Unsure since thats the most logical name
STLs -> 3dmodels. Might be good to rename for people new to 3d printing.

**Comment by jesserockz** [comment]
I don't think renaming the folders just for the sake of getting them lowercase is really that helpful at this point in time.
@adonno, It's your project, you make the decision...

**Comment by Landrash** [comment]
Closing since it might inadvertently impact users.

**Pull request closed without merging**
